#!/usr/bin/env bash
# Hardware facts: a versioned, flat KEY=value file describing the machine in
# terms the rest of the repository is allowed to branch on.
#
# Two rules make this safe to publish and safe to consume:
#
#   1. A CLOSED allowlist. Only the keys declared below may ever be emitted. A
#      detector that learns something new cannot leak it into the file — it has
#      to be added here first, in review. This is what keeps serials, MAC
#      addresses, hostnames, EDID strings, PCI bus addresses and usernames out
#      of a file that ends up in bug reports. `cpu_temp_path` is a /sys path
#      and therefore allowed: an hwmon index identifies a driver's probe order,
#      not the person holding the machine.
#   2. A schema version. Consumers call facts_require_schema and refuse a file
#      they do not understand, rather than silently mis-reading a future format.
#
# Sourced, not executed. Requires lib/kv.sh.

FACTS_SCHEMA=1

# The allowlist. `gpu_families` (catalogue family ids such as nvidia_open) is
# derived from gpu_devices by the GPU catalogue, lib/gpu.sh, not detected.
FACTS_ALLOWED_KEYS=(
	FACTS_SCHEMA
	chassis
	virt
	has_battery
	has_backlight
	has_touchpad
	has_wifi
	has_bluetooth
	cpu_temp_path
	gpu_vendors
	gpu_devices
	gpu_families
	gpu_hybrid
	kernels
	needs_dkms
	secure_boot
	monitor_count
	max_scale
)

# facts_key_allowed KEY
facts_key_allowed() {
	local candidate="$1" key
	for key in "${FACTS_ALLOWED_KEYS[@]}"; do
		[[ "$key" == "$candidate" ]] && return 0
	done
	# A deploy-time guard may also test a setting, as setting_<key>, when
	# lib/settings.sh is loaded. Such a key never enters a facts file:
	# facts_emit writes the allowlist above and nothing else.
	if [[ "$candidate" == setting_* && -v SETTINGS_ALLOWED_KEYS ]]; then
		for key in "${SETTINGS_ALLOWED_KEYS[@]}"; do
			[[ "setting_$key" == "$candidate" ]] && return 0
		done
	fi
	return 1
}

# facts_emit ARRAY_NAME FILE — write the allowlisted subset of ARRAY_NAME to
# FILE, stamped with the current schema. A key outside the allowlist is dropped
# and reported on stderr: silently discarding it would hide a detector bug, and
# failing outright would let one bad key block every other fact.
facts_emit() {
	local -n __facts_src="$1"
	local file="$2" key status=0
	local -A filtered=()

	for key in "${!__facts_src[@]}"; do
		if facts_key_allowed "$key"; then
			filtered["$key"]="${__facts_src["$key"]}"
		else
			printf 'facts: refusing key outside the allowlist: %s\n' "$key" >&2
			status=1
		fi
	done

	# shellcheck disable=SC2034  # passed by name to kv_write below
	filtered[FACTS_SCHEMA]="$FACTS_SCHEMA"
	kv_write "$file" filtered '# Generated by scripts/hardware-facts.sh. Do not edit; use the override file.'
	return "$status"
}

# facts_load ARRAY_NAME FILE... — load files in order into ARRAY_NAME. Later
# files win, which is how the user's override file beats the generated one.
facts_load() {
	# The array is forwarded BY NAME, never through a local nameref: a nameref
	# here would make kv_load's own nameref circular.
	local target_name="$1"
	shift
	local file loaded=1
	for file in "$@"; do
		[[ -r "$file" ]] || continue
		kv_load "$file" "$target_name"
		loaded=0
	done
	return "$loaded"
}

# facts_require_schema FILE [EXPECTED] — refuse a file written by a different
# schema version instead of guessing at its meaning.
facts_require_schema() {
	local file="$1" expected="${2:-$FACTS_SCHEMA}" found
	if ! found="$(kv_get "$file" FACTS_SCHEMA)"; then
		printf 'facts: %s carries no FACTS_SCHEMA stamp\n' "$file" >&2
		return 1
	fi
	if [[ "$found" != "$expected" ]]; then
		printf 'facts: %s is schema %s, this code speaks schema %s\n' "$file" "$found" "$expected" >&2
		return 1
	fi
}

# facts_get FILE KEY [DEFAULT] — read one fact. A key outside the allowlist is
# a programming error in the caller, not a missing value, so it is reported.
facts_get() {
	local file="$1" key="$2" default="${3:-}" value
	if ! facts_key_allowed "$key"; then
		printf 'facts: %s is not an allowlisted fact key\n' "$key" >&2
		return 2
	fi
	if value="$(kv_get "$file" "$key")"; then
		printf '%s' "$value"
		return 0
	fi
	printf '%s' "$default"
	return 1
}
